---
sidebar: sidebar 
permalink: concepts/gssc.html 
keywords: Keystone support, service request, support ticket 
summary: 如果您需要帮助，请联系NetApp Keystone支持团队。 
---
= 获取有关Keystone的帮助
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone支持团队和Keystone成功经理 (KSM) 负责为您的Keystone订阅提供服务。如果您需要帮助，可以联系Keystone支持团队。



== NetApp Keystone支持

NetApp为NetApp Keystone客户提供远程运营服务。这些服务涵盖了存储管理活动的一系列操作原则。这些服务包括资产和配置管理、容量和性能管理、变更管理、事件、事故和问题管理、服务请求履行和报告。  NetApp按要求展示控制状态和支持证据。



== 追加信息

NetApp使用 ITOM 监控解决方案主动监控并连接到NetApp Keystone环境进行故障排除。


NOTE: 在合作伙伴运营模式中，租户和子租户的服务请求被分配给合作伙伴的服务台。合作伙伴的支持工具可能与 ITOM 解决方案集成。

有关Keystone服务的更多信息，请参阅：

* NetApp Keystonehttps://www.netapp.com/us/solutions/keystone/index.aspx["https://www.netapp.com/us/solutions/keystone/index.aspx"^]
* NetApp产品文档https://docs.netapp.com["https://docs.netapp.com"^]




== Keystone支持监控

NetApp Keystone支持监控您的产品和订阅服务的健康状况、提供远程支持并与您的Keystone成功经理合作。

.Keystone成功经理
Keystone成功经理 (KSM) 与您密切合作，为您提供Keystone服务，并向您提供每周或每月的账单和运营报告。您的NetApp Keystone协议中指定了这些责任。



== 生成服务请求

在入职期间，如果您获得了访问和使用 Netapp Keystone ServiceNow 的凭据，您可以使用该门户针对与您的Keystone订阅相关的问题生成服务请求：

https://netappgssc.service-now.com/csm[]

在提出服务请求之前，请确保您已准备好系统详细信息、日志和相关信息。当您提出服务请求时， Keystone支持团队会收到支持票并访问信息以进行故障排除。您可以关注您的 ServiceNow 票证以了解状态和解决方案。

有关添加支持包的信息，请参阅link:../installation/monitor-health.html["生成并收集支持包"]。

如果您有需要升级的未结案例/票据，请发送电子邮件至以下地址之一：keystone.services@netapp.com keystone.escalations@netapp.com
