---
sidebar: sidebar 
permalink: concepts/metrics.html 
keywords: metrics, GiB, IOPS, latency, durability, v2, version 2 
summary: NetApp Keystone STaaS 服务使用多个术语来衡量指标。在使用Keystone服务第 2 版时，您可能希望了解有关这些术语的更多信息。 
---
= Keystone中使用的指标和定义
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS 服务使用多个术语来衡量指标。在使用Keystone时，您可能想要了解有关这些术语的更多信息。

Keystone STaaS 服务中使用以下术语和定义来衡量指标：

* 容量：以 GiB、TiB 和 PiB 为单位。
* IO 密度：IOPS/TiB：基于工作负载消耗的总空间，每秒处理的输入/输出操作数，以太字节为单位。
* 服务可用性
* 准确数据访问的持久性
* 延迟和速度




== 指标测量

* *以 GiB、TiB 和 PiB 为单位的容量测量*：使用 1024 为基数测量数据存储容量（1 GiB = 1024^3^ 字节、1 TiB = 1024^4^ 字节和 1 PiB = 1024^5^ 字节）。
* *IOPS/TiB 中的操作计数器图表*：应用程序请求的每秒协议操作数除以工作负载使用的卷大小。
* *可用性*：以服务成功响应的 I/O 请求数除以向服务发出的 I/O 请求总数的百分比来衡量。这是在一个月的服务划分时测量的，不包括计划的服务停机时间或设施、网络或客户提供的其他服务的不可用时间。
* *耐用性*：在不损失保真度的情况下访问的数据百分比，不包括客户造成的删除或损坏。
* *延迟*：在服务边界（存储控制器 I/O 端口）测量从客户端收到的 I/O 请求的服务时间。




=== 吞吐量性能指标

吞吐量性能指标仅适用于基于以下内容的文件和块服务：

* 32 KB 块大小
* 70% 读取/30% 写入 I/O 组合




=== IO密度的变化

以 IOPS/TiB 和/或 MBps/TiB 计算的 IO 密度取决于以下因素：

* 工作负载特征
* 延迟，不包括以下内容：
+
** 应用程序延迟
** 主机延迟
** 在控制器端口之间传输数据时客户网络的延迟
** 在FabricPool的情况下，与数据传输到对象存储相关的开销延迟
** QoS 自动应用延迟，使 IO 保持在服务级别最大值范围内


* 计入已用容量的用户和 Snapshot 副本数据
* 每个ONTAP卷上分配的绝对最小 IOPS，无论卷中的数据量是多少：
+
** 极限：1,000 IOPS
** 高级：500 IOPS
** 性能、标准和价值：75 IOPS


* 在使用高级数据保护附加服务时，目标延迟仅适用于服务来自本地存储的 IO 请求。




=== 卷 AQoS

每个ONTAP卷都应应用适用的自适应服务质量 (AQoS) 策略。否则，每个未应用 AQoS 策略的卷内的容量将按照最高服务级别的费率计费。
