---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Billing and miscellaneous scenarios 
summary: 了解特定配置的Keystone计费，包括克隆卷、高级数据保护等。 
---
= Keystone计费的其他场景
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
了解特定配置的Keystone计费可以帮助您优化服务使用并管理成本。配置包括克隆卷、高级数据保护、临时卷、QoS 策略、 SnapMirror目标、LUN 和系统/根卷。



== 克隆卷的计费

如果在ONTAP中克隆了卷并且您使用它们来备份和恢复数据，则您可以继续使用克隆而无需任何额外付款。但是，如果克隆卷在很长一段时间内用于您企业中的任何其他目的，则需要付费。

请注意以下事项：

* 只要克隆卷的大小小于父卷的 10%（克隆卷中使用的物理容量与父卷中使用的物理容量之比），克隆卷就免费。
* 克隆卷没有 24 小时的宽限期。仅考虑克隆的大小。
* 一旦克隆卷超过父卷物理大小的 10%，克隆卷就会被视为标准卷（逻辑使用容量）。




== 高级数据保护计费

高级数据保护使用NetApp MetroCluster在两个物理上分离的集群之间镜像数据。对于MetroCluster镜像聚合，数据写入两次，每个集群一次。 Keystone服务对双方的消费进行独立计费，从而产生两条相同的消费记录。附加费用适用于订阅中的所有容量，无论数据是在源处，还是镜像或非镜像数据。

每个MetroCluster站点都有自己的订阅和计费。对于MetroCluster配置，使用情况测量考虑了两个站点之间的存储利用情况。如果您的MetroCluster设置中每个站点有 100 TiB，则每个站点上只有 50 TiB 被主动使用，而每个站点上剩余的 50 TiB 则用作镜像备份。高级数据保护附加费用是根据这 100 TiB 的总活动使用量计算的，并通过各自的订阅在两个站点之间分摊，每个站点 50 TiB。

如果您通过ONTAP系统管理器（系统管理器）或Active IQ Unified Manager（统一管理器）监控集群，您可能会发现这些工具报告的消耗量与Keystone之间存在差异。系统管理器和统一管理器不报告镜像（远程）集群上的卷，因此，报告的消耗指标仅为Keystone服务报告的消耗指标的一半。

.示例：
站点 A 和站点 B 采用MetroCluster配置进行设置。当用户在站点 A 创建 10 TB 的卷时，站点 B 中也会创建相同的 10 TB 卷。KeystoneKeystone每个站点的消耗量为 10 TB，总共增加 20 TB。系统管理器和统一管理器报告在站点 A 中创建的 10 TB 卷，但没有报告在站点 B 中创建的 10 TB 卷。

此外，在具有高级数据保护的Keystone系统上创建的所有卷都将计入高级数据保护的消耗，无论这些卷是否镜像。



== 临时卷计费

有时， ONTAP在移动卷时会创建临时 (TMP) 卷。这些临时卷是短暂的，并且这些卷上的消耗不计入账单。



== 计费和自适应 QoS 策略

Keystone根据服务水平来衡量消费。每个服务级别都与特定的自适应服务质量 (QoS) 策略相关联。在部署期间，您将被告知所订阅的Keystone服务的每个自适应 QoS 策略的详细信息。在存储管理操作期间，请确保您的卷根据您订阅的服务级别分配了适当的自适应 QoS 策略，以避免意外计费。有关ONTAP中自适应 QoS 策略的更多信息，请参阅link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["通过QoS概述保证吞吐量"^]。



== SnapMirror目标计费

SnapMirror目标卷的定价由源上分配的服务级别的自适应 QoS 策略控制。但是，如果源没有关联的自适应 QoS 策略，则目的地将根据最低可用服务级别进行计费。



== LUN 计费

对于 LUN，遵循与自适应 QoS 策略管理的卷相同的计费模式。如果在 LUN 上设置了单独的自适应 QoS 策略，则：

* LUN 的大小是根据该 LUN 的相关服务级别来计算消耗的。
* 卷中剩余的空间（如果有）将根据卷上设置的服务级别的自适应 QoS 策略进行收费。




== 系统卷和根卷

系统卷和根卷作为Keystone服务整体监控的一部分进行监控，但不计算或计费。这些卷的消耗无需计费。
