---
sidebar: sidebar 
permalink: concepts/pricing.html 
keywords: pricing, billing introduction, Keystone billing 
summary: Keystone提供按需付费模式，满足您灵活且可扩展的消费需求。 
---
= Keystone定价
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS 按使用量付费订阅服务提供灵活且可扩展的消费，并为您的存储需求提供可预测的预付定价。

Keystone为您提供以下计费功能：

* 您可以根据 IOPS 和延迟承诺容量付费，以满足各种工作负载需求。不同的性能服务层级 - Extreme、Premium、Performance、Standard、Value 和 Object 使您能够根据购买的性能服务级别管理存储。
* 它为承诺的容量提供可预测的计费，并为可变（突发）容量使用提供按使用付费。
* 您可以为硬件、核心操作系统和支持选择一个捆绑价格，价格为 1 美元/TiB。对于每种存储类型、文件、块、对象或云存储服务，您都有一张发票。
* 您可以选择灵活的服务期限和付款方式，例如按月、按季度或按年。


Keystone计费基于承诺容量和可变突发消耗。

有关Keystone支持的不同容量的信息，请参阅link:../concepts/supported-storage-capacity.html["Keystone支持的存储容量"]。

*相关信息*

* link:../concepts/committed-capacity-billing.html["根据承诺容量计费"]
* link:../concepts/consumed-capacity-billing.html["根据消耗容量进行计量"]
* link:../concepts/burst-consumption-billing.html["根据突发消费计费"]
* link:../concepts/misc-volume-billing.html["根据杂项卷类型计费"]
* link:../concepts/billing-schedules.html["计费时间表"]

