---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: Keystone STaaS 服务支持ONTAP和StorageGRID。 
---
= Keystone支持的存储
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS 服务支持使用ONTAP 的文件和块存储、使用StorageGRID的对象存储以及Cloud Volumes ONTAP。

Keystone STaaS 为您的存储提供标准和可选服务。

* Keystone STaaS 标准服务*：标准服务包含在基本订阅内，不单独收费。

* Keystone STaaS 附加服务*：这些是可选的、收费的服务，在标准Keystone STaaS 订阅服务的基础上提供额外的实用程序和好处。

Keystone STaaS服务可以同时使用。例如，云存储订阅可以具有与文件、块和对象存储订阅相同的术语。可以在现有存储订阅的服务期限内的任何时候包含云服务。但是，如果您不打算续订现有的文件、块和对象订阅，则在订阅的最后 90 天内无法添加云存储订阅。



== 文件、块和对象存储服务

适用于ONTAP文件和块存储以及StorageGRID对象存储的Keystone STaaS 服务支持多种功能和协议，如下表所述：

|===
| 存储 | 平台 | 协议 | 支持的功能 


 a| 
文件存储
 a| 
ONTAP
 a| 
NFS 和 CIFS
 a| 
支持的ONTAP功能：

* FlexVol
* FlexGroup
* Snapshot 副本
* SnapMirror （异步）
* SnapVault
* SnapLock Enterprise
* FabricPool/云分层
* SnapRestore
* FlexClone
* SnapCenter （包含许可证，但不属于Keystone服务的一部分，并且不保证管理）
* 自主勒索软件防护^1^




 a| 
块存储
 a| 
ONTAP
 a| 
FC 和 iSCSI
 a| 
支持的ONTAP功能：

* FlexVol
* FlexGroup
* Snapshot 副本
* SnapMirror （异步）
* SnapVault
* SnapLock Enterprise
* FabricPool/云分层
* SnapRestore
* FlexClone
* SnapCenter （包含许可证，但不属于Keystone服务的一部分，并且不保证管理）




 a| 
对象存储
 a| 
StorageGRID
 a| 
S3
 a| 
支持跨多个站点的多种信息生命周期管理 (ILM) 策略^2^

|===

NOTE: ^1^ 有关ONTAP中的勒索软件防护的信息，请参阅 https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["自主勒索软件防护"^]。  ^2^ 每个站点都需要单独订阅。



== 云存储服务

Keystone STaaS 提供云存储服务。  Keystone STaaS 支持 Amazon Web Services (AWS)、Microsoft Azure 和 Google Cloud Platform 上的Cloud Volumes ONTAP数据管理功能。


NOTE: NetApp不提供Cloud Volumes ONTAP所需的基于超标量的计算、存储和网络服务作为Keystone STaaS 订阅的一部分；这些订阅需要直接从超标量云服务提供商处采购。
