---
sidebar: sidebar 
permalink: installation/install-itom-windows.html 
keywords: Windows installation Keystone, ITOM Collector installation 
summary: 在基于 Windows 的系统上安装 ITOM Collector。 
---
= 在 Windows 系统上安装 ITOM Collector
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
通过下载 ITOM Collector 安装文件、运行 InstallShield 向导并输入所需的监控凭据，在 Windows 系统上安装 ITOM Collector。


NOTE: Keystone支持团队提供了一个动态链接来下载 ITOM Collector 安装文件，该文件将在两小时后过期。

您可以根据需要在 Linux 系统上安装它。要在 Linux 系统上安装 ITOM Collector，请参阅link:../installation/install-itom-linux.html["在 Linux 系统上安装 ITOM Collector"]。

按照以下步骤在 Windows 服务器上安装 ITOM 收集器软件：

.开始之前
确保在 Windows 服务器的本地安全策略设置中的本地策略/用户权限分配下授予 ITOM Collector 服务*作为服务登录*。

.步骤
. 将 ITOM 收集器安装文件下载到您的 Windows 服务器。
. 打开安装文件以启动 InstallShield 向导。
. 接受最终用户许可协议 (EULA)。  InstallShield 向导提取必要的二进制文件并提示您输入凭据。
. 输入 ITOM Collector 将在其下运行的帐户的凭据：
+
** 如果 ITOM Collector 没有监控其他 Windows 服务器，请使用本地系统。
** 如果 ITOM Collector 正在监控同一域中的其他 Windows 服务器，请使用具有本地管理员权限的域帐户。
** 如果 ITOM Collector 正在监控不属于同一域的其他 Windows 服务器，请使用本地管理员帐户并使用本地管理员凭据连接到每个资源。您可以选择设置密码以使其不会过期，以减少 ITOM Collector 与其监控资源之间的身份验证问题。


. 选择收集器尺寸。默认值是根据安装文件推荐的大小。除非您有特殊要求，否则请按照建议的尺寸进行。
. 选择“下一步”开始安装。您可以使用已填充的文件夹或选择其他文件夹。状态框显示安装进度，然后出现 InstallShield Wizard 完成对话框。


.下一步是什么？
安装成功后，请联系Keystone支持团队通过 ITOM 支持门户验证 ITOM Collector 是否安装成功。验证后， Keystone支持团队将远程配置 ITOM Collector，包括进一步的设备发现和监控设置，并在配置完成后发送确认。如有任何疑问或需要更多信息，请联系 keystone.services@netapp.com。
