---
sidebar: sidebar 
permalink: release-notes/fixed-issues.html 
keywords: fixed issues 
summary: NetApp Keystone STaaS 服务先前版本中发现的问题已在后续版本中得到修复。 
---
= 已修复Keystone STaaS 中的问题
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS 服务先前版本中发现的问题已在后续版本中得到修复。

[cols="3*"]
|===
| 问题描述 | 修复后 | 已在发布中修复 


 a| 
Digital Advisor仪表板中配置了MetroCluster配置的订阅的消费趋势图中缺少突发阈值线，显示不正确的 *超出突发限制* 状态。
 a| 
固定的
 a| 
2025年8月28日



 a| 
在“*Assets*”选项卡中， StorageGRID的资产不可见。
 a| 
固定的
 a| 
2025年6月19日



 a| 
对于高级数据保护服务级别，在“消费趋势”选项卡中，图表显示了主站点和镜像站点的分割。
 a| 
图表不再显示主站点和镜像站点的分割。
 a| 
2025年6月19日



 a| 
当使用 Debian 软件包安装的现有Keystone Collector 尝试通过Keystone Collector 管理 TUI 配置 HTTP 代理或启用 Unified Manager 时，TUI 将变得无响应。
 a| 
固定的
 a| 
2025年5月19日



 a| 
由于缺少通用设置， Keystone Collector for StorageGRID无法正确配置。
 a| 
固定的
 a| 
2025年5月12日



 a| 
Keystone Collector 无法收集运行低于 9.11 版本的ONTAP集群的使用情况数据。
 a| 
固定的
 a| 
2025年4月30日



 a| 
链接订阅的消费值显示不正确的负数，导致总承诺使用量显示不准确的高。
 a| 
固定的
 a| 
2025年4月14日



 a| 
无法在“消费趋势”选项卡中查看一些订阅的服务级别的历史数据。
 a| 
固定的
 a| 
2025年4月14日



 a| 
Digital Advisor仪表板上的 *Watchlist* 中缺少 * Keystone Subscriptions* 选项，*Reports* 中缺少 *Subscription Number* 选项。
 a| 
固定的
 a| 
2025年3月19日



 a| 
从Digital Advisor仪表板创建或修改监视列表后，*监视列表*中缺少一些Keystone订阅。
 a| 
固定的
 a| 
2025年3月19日



 a| 
无法在“消费趋势”选项卡中查看与已过期且使用相同跟踪 ID 但不同服务级别续订的订阅相关的服务级别的历史数据。
 a| 
固定的
 a| 
2025年3月19日



 a| 
从 * Keystone订阅* 页面上的 *订阅* 选项卡中选择超过 10-12 个订阅时，无法生成订阅报告。
 a| 
固定的
 a| 
2025年1月8日



 a| 
对于 StorageGrid 订阅，*卷和对象*选项卡中的*卷摘要*子选项卡无法加载。
 a| 
固定的
 a| 
2024年11月21日



 a| 
当导航到“*消费趋势*”选项卡时，“*起始日期*”字段默认显示未来日期，用于选择日期范围。
 a| 
固定的
 a| 
2024年9月4日



 a| 
设置 AQoS 策略时， Keystone Collector 管理 TUI 变得无响应。
 a| 
固定的
 a| 
2024年8月7日



 a| 
当从“*容量趋势*”选项卡中的“容量趋势*”选项中选择与当前日期对应的日期作为上个月的开始和结束日期时，使用情况图表将显示超出指定单日时间段的数据。
 a| 
使用情况图表现在可以正确显示指定单日期间的数据。
 a| 
2024年6月27日



 a| 
对于未配置MetroCluster配置的订阅，*容量趋势*选项卡中的*CVO Primary* 和 *CVO Secondary* 服务级别不提供历史累计突发数据。
 a| 
固定的
 a| 
2024年6月21日



 a| 
AutoSupport订阅的“卷详细信息”选项卡上列出的对象存储消耗值显示不正确。
 a| 
对象存储的消耗值现在可以正确显示。
 a| 
2024年6月21日



 a| 
无法在使用MetroCluster配置配置的AutoSupport订阅的 *Assets* 选项卡中查看集群级别信息。
 a| 
固定的
 a| 
2024年6月21日



 a| 
如果从“容量趋势”选项卡生成的 CSV 报告中的“帐户名称”列包含带逗号的帐户名称，则Keystone数据会在 CSV 报告中错位 `(,)`。
 a| 
Keystone数据在 CSV 报告中正确对齐。
 a| 
2024年5月29日



 a| 
即使消耗量低于承诺的容量，也可以从“容量趋势”选项卡显示累计突发使用情况。
 a| 
固定的
 a| 
2024年5月29日



 a| 
*容量趋势*选项卡中的*当前突发*索引图标的工具提示文本不正确。
 a| 
显示正确的工具提示文本“_当前正在消耗的突发容量量。请注意，这是针对当前结算期，而不是选定的日期范围。_”
 a| 
2024年3月28日



 a| 
如果Keystone数据在 24 小时内不存在，则AutoSupport订阅将无法提供有关 AQoS 不兼容卷和MetroCluster合作伙伴的信息。
 a| 
固定的
 a| 
2024年3月28日



 a| 
如果为仅满足一个服务级别的 AQoS 合规性的卷分配了两个服务级别，则“*卷摘要*”和“*卷详细信息*”选项卡上列出的 AQoS 不合规卷的数量偶尔会不匹配。
 a| 
固定的
 a| 
2024年3月28日



 a| 
AutoSupport订阅的“*资产*”选项卡上没有可用信息。
 a| 
固定的
 a| 
2024年3月14日



 a| 
如果在分层和对象存储的费率计划均适用的环境中同时启用MetroCluster和FabricPool ，则可能会错误地得出镜像卷（组成卷和FabricPool卷）的服务级别。
 a| 
正确的服务级别已应用于镜像卷。
 a| 
2024年2月29日



 a| 
对于某些具有单一服务级别或费率计划的订阅，“*Volumes*”选项卡报告的 CSV 输出中缺少 AQoS 合规性列。
 a| 
合规性列在报告中可见。
 a| 
2024年2月29日



 a| 
在某些MetroCluster环境中，在“性能”选项卡中的 IOPS 密度图表中偶尔检测到异常。这是由于卷与服务级别的映射不准确造成的。
 a| 
图表显示正确。
 a| 
2024年2月29日



 a| 
突发消费记录的使用情况指示器显示为琥珀色。
 a| 
指示器显示为红色。
 a| 
2023年12月13日



 a| 
容量趋势、当前使用情况和性能选项卡中的日期范围和数据未转换为 UTC 时区。
 a| 
所有选项卡中的查询和数据的日期范围均以 UTC 时间（服务器时区）显示。选项卡上的每个日期字段也显示 UTC 时区。
 a| 
2023年12月13日



 a| 
选项卡和下载的 CSV 报告之间的开始日期和结束日期不匹配。
 a| 
固定的。
 a| 
2023年12月13日

|===