---
sidebar: sidebar 
permalink: release-notes/known-limitations.html 
keywords: limitations, known limitations in Keystone STaaS 
summary: 已知限制标识了该产品的此版本不支持或不能与其正确互操作的平台、设备或功能。仔细审查这些限制。 
---
= Keystone STaaS 的已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
已知限制是指Keystone STaaS 服务或组件不支持或无法正确互操作的平台、设备或功能。仔细审查这些限制。



== Keystone Collector 的限制



=== 启用StorageGRID SSO 后Keystone Collector 身份验证失败

当StorageGRID系统启用单点登录 (SSO) 时， Keystone Collector 不支持计量。日志中显示以下错误消息：

`panic: json: cannot unmarshal object into Go struct field AuthResponse.data of type string`

请参阅知识库文章link:https://kb.netapp.com/hybrid/Keystone/Collector/Keystone_Collector_fails_to_authenticate_with_StorageGRID_in_SSO_Mode["Keystone Collector 在 SSO 模式下无法通过StorageGRID进行身份验证"^]以获取信息和解决方案。



=== Keystone Collector 无法在 vSphere 8.0 Update 1 上启动

安装了 VMware vSphere 8.0 Update 1 的Keystone Collector 虚拟机 (VM) 无法启动，并显示以下错误消息：

`Property 'Gateway' must be configured for the VM to power on.`

请参阅知识库文章link:https://kb.netapp.com/hybrid/Keystone/Collector/Keystone_Collector_fails_to_start_on_vSphere_8.0_U1["Keystone Collector 无法在 vSphere 8.0 U1 上启动"^]以获取信息和解决方案。



=== 无法通过 Kerberos 生成支持包

如果使用 Kerberos 通过 NFSv4 挂载Keystone Collector 主目录，则不会生成支持包，并会显示以下错误消息：

`subprocess.CalledProcessError: Command '['sosreport', '--batch', '-q', '--tmp-dir', '/home/<user>']' returned non-zero exit status 1.`

请参阅知识库文章 https://kb.netapp.com/hybrid/Keystone/Collector/Keystone_Collector_fails_to_generate_support_bundle_on_Kerberized_home_directory["Keystone Collector 无法在 Kerberized 主目录上生成支持包"^]以获取信息和解决方案。



=== Keystone Collector 无法与特定网络范围内的主机通信

Keystone `ks-collector`服务正在运行。请参阅知识库文章link:https://kb.netapp.com/hybrid/Keystone/Collector/Keystone_Collector_container_conflict_with_customer_network["Keystone Collector 容器与客户网络冲突"^]以获取信息和解决方案。



=== Keystone Collector 无法验证客户根 SSL CA 证书

如果在检查 SSL/TLS 流量的环境中在边界防火墙上启用了 SSL/TLS 检查， Keystone Collector 将无法建立 HTTPS 连接，因为客户的根 CA 证书不受信任。

有关详细信息和解决方法，请参阅link:..//installation/configuration.html#trust-a-custom-root-ca["信任自定义根 CA"^]或知识库文章link:https://kb.netapp.com/hybrid/Keystone/Collector/Keystone_Collector_cannot_verify_Customer_Root_SSL_CA_certificate["Keystone Collector 无法验证客户根 SSL CA 证书"^]。
